services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: jwt-auth-go
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: jwt-auth-go
      DB_PORT: "5432"
      SSL_MODE: "disable"
      JWT_SECRET: "nB1k0l3Mt29Xqv5yYz7bG8jKp4dQeR6hUj3mNz8xPw7r9A2tLkWv8FcYbVzOjIlP"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data:
